Repository smartlook/code-quality, pull requests merged in 2022-05, with the labels that each got.

#66 chore(deps): pin dependencies
  package.json
  pnpm-lock.yaml
Labels: dependencies, tooling

#74 chore(deps): update renovatebot/github-action action to v32.63.1
  .github/workflows/renovate.yml
Labels: dependencies, tooling

#76 fix(deps): pin dependencies
  packages/eslint/eslint-config-base/package.json
  packages/eslint/eslint-config-node/package.json
  packages/eslint/eslint-config-prettier/package.json
  packages/eslint/eslint-config-typescript/package.json
  pnpm-lock.yaml
Labels: styling

#78 chore(deps): update actions/setup-node action to v3
  .github/workflows/release.yml
Labels: dependencies, tooling

#79 chore(deps): update commitlint monorepo to v17 (major)
  package.json
  pnpm-lock.yaml
Labels: dependencies, tooling

#77 fix(deps): pin dependencies
  packages/eslint/eslint-config-prettier/package.json
  packages/eslint/eslint-config-typescript/package.json
  pnpm-lock.yaml
Labels: dependencies, tooling, styling

#81 fix(deps): update dependency eslint to v8.16.0
  packages/eslint/eslint-config-base/package.json
  packages/eslint/eslint-config-node/package.json
  packages/eslint/eslint-config-prettier/package.json
  packages/eslint/eslint-config-typescript/package.json
  pnpm-lock.yaml
Labels: styling

#80 chore(deps): update renovatebot/github-action action to v32.64.2
  .github/workflows/renovate.yml
Labels: dependencies, tooling
